const governorates = [
  { id: 1, name: "Beirut" },
  { id: 2, name: "Mount Lebanon" },
  { id: 3, name: "North" },
  { id: 4, name: "Bekaa" },
  { id: 5, name: "Nabatieh" },
  { id: 6, name: "South" },
];

const constituencies = [
  { id: 1, name: "Beirut I (Capital, Diverse)", governorate_id: 1, seats: 8 },
  { id: 2, name: "Beirut II (Capital, Diverse)", governorate_id: 1, seats: 10 },
  { id: 3, name: "Bekaa I (Baalbek-Hermel)", governorate_id: 4, seats: 10 },
  { id: 4, name: "Bekaa II (Zahle)", governorate_id: 4, seats: 7 },
  {
    id: 5,
    name: "Bekaa III (West Bekaa-Rachaya)",
    governorate_id: 4,
    seats: 6,
  },
  {
    id: 6,
    name: "Mount Lebanon I (Jbeil-Keserwan)",
    governorate_id: 2,
    seats: 8,
  },
  { id: 7, name: "Mount Lebanon II (North Metn)", governorate_id: 2, seats: 8 },
  { id: 8, name: "Mount Lebanon III (Baabda)", governorate_id: 2, seats: 6 },
  { id: 9, name: "Mount Lebanon IV (Aley)", governorate_id: 2, seats: 6 },
  { id: 10, name: "Mount Lebanon V (Chouf)", governorate_id: 2, seats: 8 },
  { id: 11, name: "North I (Akkar)", governorate_id: 3, seats: 7 },
  { id: 12, name: "North II (Dinniyeh-Minieh)", governorate_id: 3, seats: 4 },
  { id: 13, name: "North III (Tripoli)", governorate_id: 3, seats: 8 },
  { id: 14, name: "South I (Saida-Jezzine)", governorate_id: 6, seats: 7 },
  { id: 15, name: "South II (Tyre-Zahrani)", governorate_id: 6, seats: 7 },
];

const districts = [
  { id: 1, name: "Beirut", governorate_id: 1 },
  { id: 2, name: "Baabda", governorate_id: 2 },
  { id: 3, name: "Aley", governorate_id: 2 },
  { id: 4, name: "Matn", governorate_id: 2 },
  { id: 5, name: "Chouf", governorate_id: 2 },
  { id: 6, name: "Byblos", governorate_id: 2 },
  { id: 7, name: "Keserwen", governorate_id: 2 },
  { id: 8, name: "Tripoli", governorate_id: 3 },
  { id: 9, name: "Zgharta", governorate_id: 3 },
  { id: 10, name: "Bsharri", governorate_id: 3 },
  { id: 11, name: "Batroun", governorate_id: 3 },
  { id: 12, name: "Koura", governorate_id: 3 },
  { id: 13, name: "Minyeh-Danniyeh", governorate_id: 3 },
  { id: 14, name: "Akkar", governorate_id: 3 },
  { id: 15, name: "Zahle", governorate_id: 4 },
  { id: 16, name: "Baalbek", governorate_id: 4 },
  { id: 17, name: "Hermel", governorate_id: 4 },
  { id: 18, name: "Western Beqaa", governorate_id: 4 },
  { id: 19, name: "Nabatieh", governorate_id: 5 },
  { id: 20, name: "Hasbaya", governorate_id: 5 },
  { id: 21, name: "Marjeyoun", governorate_id: 5 },
  { id: 22, name: "Bint Jbeil", governorate_id: 5 },
  { id: 23, name: "Sidon", governorate_id: 6 },
  { id: 24, name: "Tyre", governorate_id: 6 },
  { id: 25, name: "Jezzine", governorate_id: 6 },
  { id: 27, name: "Rashaya", governorate_id: 4 },
];

const villages = [
  { id: 1, name: "Beirut", district_id: 1 },
  { id: 157, name: "Arsoon", district_id: 6 },
  { id: 158, name: "Al Hazmieh", district_id: 6 },
  { id: 159, name: "Al Hadesh", district_id: 6 },
  { id: 160, name: "Sbenneh", district_id: 6 },
  { id: 161, name: "Harat Al Batm", district_id: 6 },
  { id: 162, name: "Al Kharayeb", district_id: 6 },
  { id: 163, name: "Al Shabanieh", district_id: 6 },
  { id: 164, name: "Al Shiyah", district_id: 6 },
  { id: 165, name: "Al Abbadieh", district_id: 6 },
  { id: 166, name: "Al Arabanieh", district_id: 6 },
  { id: 167, name: "Al Dalyeh", district_id: 6 },
  { id: 168, name: "Al Ghobeiri", district_id: 6 },
  { id: 169, name: "Al Qarya", district_id: 6 },
  { id: 170, name: "Al Qasaybeh", district_id: 6 },
  { id: 171, name: "Al Qalaa", district_id: 6 },
  { id: 172, name: "Al Kaniseh", district_id: 6 },
  { id: 173, name: "Al Hilalieh", district_id: 6 },
  { id: 174, name: "Btekhnay", district_id: 6 },
  { id: 175, name: "Bourj Al Barajneh", district_id: 6 },
  { id: 176, name: "Bzebdin", district_id: 6 },
  { id: 177, name: "Bsaba", district_id: 6 },
  { id: 178, name: "Batshiyeh", district_id: 6 },
  { id: 179, name: "Batshiyeh", district_id: 6 },
  { id: 180, name: "Al Loueizeh", district_id: 6 },
  { id: 181, name: "Baalshemieh", district_id: 6 },
  { id: 182, name: "Bmariam", district_id: 6 },
  { id: 183, name: "Tahweitat Al Ghadeer", district_id: 6 },
  { id: 184, name: "Al Laylakeh", district_id: 6 },
  { id: 185, name: "Al Marajeh", district_id: 6 },
  { id: 186, name: "Tarshish", district_id: 6 },
  { id: 187, name: "Jouar Al Hoz", district_id: 6 },
  { id: 188, name: "Jouret Arsoon", district_id: 6 },
  { id: 189, name: "Harat Al Sit", district_id: 6 },
  { id: 190, name: "Harat Horeik", district_id: 6 },
  { id: 191, name: "Hasbaya Al Matn", district_id: 6 },
  { id: 192, name: "Hammana", district_id: 6 },
  { id: 193, name: "Deir Al Harf", district_id: 6 },
  { id: 194, name: "Ras Al Harf", district_id: 6 },
  { id: 195, name: "Ras Al Matn", district_id: 6 },
  { id: 196, name: "Rweiset Al Balout", district_id: 6 },
  { id: 197, name: "Shweit", district_id: 6 },
  { id: 198, name: "Salima", district_id: 6 },
  { id: 199, name: "Araya", district_id: 6 },
  { id: 200, name: "Falougha", district_id: 6 },
  { id: 201, name: "Al Khalawat", district_id: 6 },
  { id: 202, name: "Furn Al Shubbak", district_id: 6 },
  { id: 203, name: "Ain Al Rummaneh", district_id: 6 },
  { id: 204, name: "Tahweitat Al Nahr", district_id: 6 },
  { id: 205, name: "Qbeiy", district_id: 6 },
  { id: 206, name: "Qartaba", district_id: 6 },
  { id: 207, name: "Qornayel", district_id: 6 },
  { id: 208, name: "Kfarselwan", district_id: 6 },
  { id: 209, name: "Kfarshima", district_id: 6 },
  { id: 210, name: "Wadi Shahrour Al Sufla", district_id: 6 },
  { id: 211, name: "Wadi Shahrour Al Ulya", district_id: 6 },
  { id: 318, name: "Adma", district_id: 7 },
  { id: 319, name: "Al Dafneh", district_id: 7 },
  { id: 320, name: "Al Bwar", district_id: 7 },
  { id: 321, name: "Al Jadida (Jadidet Ghazir)", district_id: 7 },
  { id: 322, name: "Harharya wa Al Qatin", district_id: 7 },
  { id: 323, name: "Al Husein", district_id: 7 },
  { id: 324, name: "Al Safra", district_id: 7 },
  { id: 325, name: "Al Adhra", district_id: 7 },
  { id: 326, name: "Al Adhr", district_id: 7 },
  { id: 327, name: "Al Aqaybeh", district_id: 7 },
  { id: 328, name: "Al Ghayneh", district_id: 7 },
  { id: 329, name: "Al Qlayaat", district_id: 7 },
  { id: 330, name: "Al Kfour", district_id: 7 },
  { id: 331, name: "Al Mayassara", district_id: 7 },
  { id: 332, name: "Al Numoura", district_id: 7 },
  { id: 333, name: "Kfar Jreif", district_id: 7 },
  { id: 334, name: "Bzammar", district_id: 7 },
  { id: 335, name: "Batkha", district_id: 7 },
  { id: 336, name: "Bqaata Ashqout", district_id: 7 },
  { id: 337, name: "Bqaata Kanaan", district_id: 7 },
  { id: 338, name: "Bqaetouteh", district_id: 7 },
  { id: 339, name: "Blouneh", district_id: 7 },
  { id: 340, name: "Jaaita", district_id: 7 },
  { id: 341, name: "Jouret Al Tarmas", district_id: 7 },
  { id: 342, name: "Jouret Badran", district_id: 7 },
  { id: 343, name: "Jounieh", district_id: 7 },
  { id: 344, name: "Hrajel", district_id: 7 },
  { id: 345, name: "Hayata", district_id: 7 },
  { id: 346, name: "Darya", district_id: 7 },
  { id: 347, name: "Daroun", district_id: 7 },
  { id: 348, name: "Harissa", district_id: 7 },
  { id: 349, name: "Dalbta", district_id: 7 },
  { id: 350, name: "Rashin", district_id: 7 },
  { id: 351, name: "Rayfoun", district_id: 7 },
  { id: 352, name: "Zaaaytreh", district_id: 7 },
  { id: 353, name: "Zouk Mosbeh", district_id: 7 },
  { id: 354, name: "Zouk Mkayel", district_id: 7 },
  { id: 355, name: "Zaytoun", district_id: 7 },
  { id: 356, name: "Suhayleh", district_id: 7 },
  { id: 357, name: "Shhatoul", district_id: 7 },
  { id: 358, name: "Jouret Mahad", district_id: 7 },
  { id: 359, name: "Shananeer", district_id: 7 },
  { id: 360, name: "Tabarja", district_id: 7 },
  { id: 361, name: "Kfaryassine", district_id: 7 },
  { id: 362, name: "Ajalton", district_id: 7 },
  { id: 363, name: "Aramoun", district_id: 7 },
  { id: 364, name: "Ashqout", district_id: 7 },
  { id: 365, name: "Ain Al Rayhaneh", district_id: 7 },
  { id: 366, name: "Aintoura", district_id: 7 },
  { id: 367, name: "Ghabaleh", district_id: 7 },
  { id: 368, name: "Ghadras", district_id: 7 },
  { id: 369, name: "Ghazir", district_id: 7 },
  { id: 370, name: "Ghosta", district_id: 7 },
  { id: 371, name: "Farya", district_id: 7 },
  { id: 372, name: "Fataqa", district_id: 7 },
  { id: 373, name: "Feitroun", district_id: 7 },
  { id: 374, name: "Kfarteyh", district_id: 7 },
  { id: 375, name: "Kfardebian", district_id: 7 },
  { id: 376, name: "Mayrouba", district_id: 7 },
  { id: 377, name: "Wata Al Joz", district_id: 7 },
  { id: 378, name: "Yahshoush", district_id: 7 },
  { id: 379, name: "Al Barouk", district_id: 5 },
  { id: 380, name: "Al Faradis", district_id: 5 },
  { id: 381, name: "Al Burjain", district_id: 5 },
  { id: 382, name: "Al Marjiyat", district_id: 5 },
  { id: 383, name: "Al Bira", district_id: 5 },
  { id: 384, name: "Al Jahiliya", district_id: 5 },
  { id: 385, name: "Al Jiyeh", district_id: 5 },
  { id: 386, name: "Al Kharayeb", district_id: 5 },
  { id: 387, name: "Al Damour", district_id: 5 },
  { id: 388, name: "Al Dibbiyeh", district_id: 5 },
  { id: 389, name: "Al Rumayleh", district_id: 5 },
  { id: 390, name: "Al Zaarouriya", district_id: 5 },
  { id: 391, name: "Al Samqaniya", district_id: 5 },
  { id: 392, name: "Al Fawwara", district_id: 5 },
  { id: 393, name: "Al Kahalouniya", district_id: 5 },
  { id: 394, name: "Al Kanisa", district_id: 5 },
  { id: 395, name: "Al Mukhtara", district_id: 5 },
  { id: 396, name: "Al Mushrif", district_id: 5 },
  { id: 397, name: "Al Matleh", district_id: 5 },
  { id: 398, name: "Al Mughayriyeh", district_id: 5 },
  { id: 399, name: "Al Naameh", district_id: 5 },
  { id: 400, name: "Harat Al Naameh", district_id: 5 },
  { id: 401, name: "Al Wardaniyeh", district_id: 5 },
  { id: 402, name: "Al Warhaniyeh", district_id: 5 },
  { id: 403, name: "Bater", district_id: 5 },
  { id: 404, name: "Batlloun", district_id: 5 },
  { id: 405, name: "Barja", district_id: 5 },
  { id: 406, name: "Brayj", district_id: 5 },
  { id: 407, name: "Bsaba", district_id: 5 },
  { id: 408, name: "Bashtfeen", district_id: 5 },
  { id: 409, name: "Batma", district_id: 5 },
  { id: 410, name: "Baaasir", district_id: 5 },
  { id: 411, name: "Harat Baaasir", district_id: 5 },
  { id: 412, name: "Baaadran", district_id: 5 },
  { id: 413, name: "Baakleen", district_id: 5 },
  { id: 414, name: "Beit El Din", district_id: 5 },
  { id: 415, name: "Jbaa", district_id: 5 },
  { id: 416, name: "Jadra", district_id: 5 },
  { id: 417, name: "Wadi Al Zayna", district_id: 5 },
  { id: 418, name: "Jadidet Al Shouf", district_id: 5 },
  { id: 419, name: "Joun", district_id: 5 },
  { id: 420, name: "Harat Jandal", district_id: 5 },
  { id: 421, name: "Hasroun", district_id: 5 },
  { id: 422, name: "Darya", district_id: 5 },
  { id: 423, name: "Dalhoun", district_id: 5 },
  { id: 424, name: "Dmeit", district_id: 5 },
  { id: 425, name: "Deir Al Qamar", district_id: 5 },
  { id: 426, name: "Deir Dourite", district_id: 5 },
  { id: 427, name: "Deir Koucheh", district_id: 5 },
  { id: 428, name: "Sableen", district_id: 5 },
  { id: 429, name: "Sarjbal", district_id: 5 },
  { id: 430, name: "Sheheem", district_id: 5 },
  { id: 431, name: "Dahr Al Maghara", district_id: 5 },
  { id: 432, name: "Anout", district_id: 5 },
  { id: 433, name: "Atreen", district_id: 5 },
  { id: 434, name: "Alaman", district_id: 5 },
  { id: 435, name: "Al Barghouniya", district_id: 5 },
  { id: 436, name: "Amatour", district_id: 5 },
  { id: 437, name: "Ameeq", district_id: 5 },
  { id: 438, name: "Ain Al Hoor", district_id: 5 },
  { id: 439, name: "Ain Zahelta", district_id: 5 },
  { id: 440, name: "Ain Qeni", district_id: 5 },
  { id: 441, name: "Ain wa Zein", district_id: 5 },
  { id: 442, name: "Ainbal", district_id: 5 },
  { id: 443, name: "Ghraifeh", district_id: 5 },
  { id: 444, name: "Ketermaya", district_id: 5 },
  { id: 445, name: "Kfarheim", district_id: 5 },
  { id: 446, name: "Kfarfaqoud", district_id: 5 },
  { id: 447, name: "Kfarqatra", district_id: 5 },
  { id: 448, name: "Kfarnabrakh", district_id: 5 },
  { id: 449, name: "Kfarnis", district_id: 5 },
  { id: 450, name: "Majdal Al Maoush", district_id: 5 },
  { id: 451, name: "Maristi", district_id: 5 },
  { id: 452, name: "Mazboud", district_id: 5 },
  { id: 453, name: "Mazraat Al Shouf", district_id: 5 },
  { id: 454, name: "Mazraat Al Dahr", district_id: 5 },
  { id: 455, name: "Maasir Al Shouf", district_id: 5 },
  { id: 456, name: "Maasir Beit El Din", district_id: 5 },
  { id: 457, name: "Niha", district_id: 5 },
  { id: 458, name: "Wadi Al Sit", district_id: 5 },
  { id: 459, name: "Aghmeed", district_id: 3 },
  { id: 460, name: "Al Basateen", district_id: 3 },
  { id: 461, name: "Al Bniyeh", district_id: 3 },
  { id: 462, name: "Al Tazaniyeh", district_id: 3 },
  { id: 463, name: "Al Rajmeh", district_id: 3 },
  { id: 464, name: "Al Ramliyeh", district_id: 3 },
  { id: 465, name: "Al Shwayfat", district_id: 3 },
  { id: 466, name: "Al Ghaboun", district_id: 3 },
  { id: 467, name: "Al Qmatieh", district_id: 3 },
  { id: 468, name: "Al Kahaleh", district_id: 3 },
  { id: 469, name: "Al Musharrafah", district_id: 3 },
  { id: 470, name: "Al Mansouriyeh", district_id: 3 },
  { id: 471, name: "Ain Al Marj", district_id: 3 },
  { id: 472, name: "Btater", district_id: 3 },
  { id: 473, name: "Bahmadoun", district_id: 3 },
  { id: 474, name: "Bkhishtieh", district_id: 3 },
  { id: 475, name: "Bdadoun", district_id: 3 },
  { id: 476, name: "Badghan", district_id: 3 },
  { id: 477, name: "Bsous", district_id: 3 },
  { id: 478, name: "Bshamoun", district_id: 3 },
  { id: 479, name: "Batlloun", district_id: 3 },
  { id: 480, name: "Baourta", district_id: 3 },
  { id: 481, name: "Blaybl", district_id: 3 },
  { id: 482, name: "Bmkeyn", district_id: 3 },
  { id: 483, name: "Bmahriyeh", district_id: 3 },
  { id: 484, name: "Baysour", district_id: 3 },
  { id: 485, name: "Howmal", district_id: 3 },
  { id: 486, name: "Dafoun", district_id: 3 },
  { id: 487, name: "Dqoun", district_id: 3 },
  { id: 488, name: "Deir Qoubel", district_id: 3 },
  { id: 489, name: "Rashmaya", district_id: 3 },
  { id: 490, name: "Rimhala", district_id: 3 },
  { id: 491, name: "Rweisat Al Naaman", district_id: 3 },
  { id: 492, name: "Sarhmoul", district_id: 3 },
  { id: 493, name: "Salfaya", district_id: 3 },
  { id: 494, name: "Souq Al Gharb", district_id: 3 },
  { id: 495, name: "Sharon", district_id: 3 },
  { id: 496, name: "Shaniyeh", district_id: 3 },
  { id: 497, name: "Chartoun", district_id: 3 },
  { id: 498, name: "Shamlan", district_id: 3 },
  { id: 499, name: "Sofar", district_id: 3 },
  { id: 500, name: "Aley", district_id: 3 },
  { id: 501, name: "Abeyeh", district_id: 3 },
  { id: 502, name: "Ain Darfil", district_id: 3 },
  { id: 503, name: "Aramoun", district_id: 3 },
  { id: 504, name: "Aytat", district_id: 3 },
  { id: 505, name: "Ain Al Jadideh", district_id: 3 },
  { id: 506, name: "Ain Al Rummeneh", district_id: 3 },
  { id: 507, name: "Ain Al Sayedeh", district_id: 3 },
  { id: 508, name: "Ain Dara", district_id: 3 },
  { id: 509, name: "Ain Anoub", district_id: 3 },
  { id: 510, name: "Ain Ksour", district_id: 3 },
  { id: 511, name: "Ainab", district_id: 3 },
  { id: 512, name: "Kfarmeyeh", district_id: 3 },
  { id: 513, name: "Kfarmatta", district_id: 3 },
  { id: 514, name: "Keyfoun", district_id: 3 },
  { id: 515, name: "Majdalaya", district_id: 3 },
  { id: 516, name: "Majdalbaana", district_id: 3 },
  { id: 517, name: "Mahattat Bahmadoun", district_id: 3 },
  { id: 654, name: "Al Jadideh", district_id: 4 },
  { id: 655, name: "Al Bouchriyeh", district_id: 4 },
  { id: 656, name: "Sadd Al Bouchriyeh", district_id: 4 },
  { id: 657, name: "Al Khinshara", district_id: 4 },
  { id: 658, name: "Al Jawaar", district_id: 4 },
  { id: 659, name: "Al Dekwaneh", district_id: 4 },
  { id: 660, name: "Mar Roukoz", district_id: 4 },
  { id: 661, name: "Dahr Al Haseen", district_id: 4 },
  { id: 662, name: "Al Dwar", district_id: 4 },
  { id: 663, name: "Al Rabiyeh", district_id: 4 },
  { id: 664, name: "Al Zalqa", district_id: 4 },
  { id: 665, name: "Emmarat Chahloub", district_id: 4 },
  { id: 666, name: "Al Shweir", district_id: 4 },
  { id: 667, name: "Ain Al Sandiyaneh", district_id: 4 },
  { id: 668, name: "Al Dbayeh", district_id: 4 },
  { id: 669, name: "Zouk Al Kharab", district_id: 4 },
  { id: 670, name: "Mar Yousef", district_id: 4 },
  { id: 671, name: "Aukar", district_id: 4 },
  { id: 672, name: "Al Atchaneh", district_id: 4 },
  { id: 673, name: "Al Ayrun", district_id: 4 },
  { id: 674, name: "Al Oyoun", district_id: 4 },
  { id: 675, name: "Al Ghabe", district_id: 4 },
  { id: 676, name: "Al Fanar", district_id: 4 },
  { id: 677, name: "Al Qaqour", district_id: 4 },
  { id: 678, name: "Al Metn", district_id: 4 },
  { id: 679, name: "Mechka", district_id: 4 },
  { id: 680, name: "Al Mahidsa", district_id: 4 },
  { id: 681, name: "Bikfaya", district_id: 4 },
  { id: 682, name: "Al Mrouj", district_id: 4 },
  { id: 683, name: "Al Mayleb", district_id: 4 },
  { id: 684, name: "Al Mansouriyeh", district_id: 4 },
  { id: 685, name: "Al Makalles", district_id: 4 },
  { id: 686, name: "Al Dechouniyeh", district_id: 4 },
  { id: 687, name: "Antelias", district_id: 4 },
  { id: 688, name: "Al Naqash", district_id: 4 },
  { id: 689, name: "Btaghreen", district_id: 4 },
  { id: 690, name: "Bourj Hammoud", district_id: 4 },
  { id: 691, name: "Brummana", district_id: 4 },
  { id: 692, name: "Baskinta", district_id: 4 },
  { id: 693, name: "Bsalim", district_id: 4 },
  { id: 694, name: "Mazhar", district_id: 4 },
  { id: 695, name: "Al Majdoub", district_id: 4 },
  { id: 696, name: "Baabdat", district_id: 4 },
  { id: 697, name: "Biyaqout", district_id: 4 },
  { id: 698, name: "Beit Al Shaar", district_id: 4 },
  { id: 699, name: "Mazraat Al Hadira", district_id: 4 },
  { id: 700, name: "Beit Chabab", district_id: 4 },
  { id: 701, name: "Al Chawiya", district_id: 4 },
  { id: 702, name: "Al Qunaytira", district_id: 4 },
  { id: 703, name: "Beit Merry", district_id: 4 },
  { id: 704, name: "Jal El Dib", district_id: 4 },
  { id: 705, name: "Bqennaya", district_id: 4 },
  { id: 706, name: "Hamlaye", district_id: 4 },
  { id: 707, name: "Dik El Mehdi", district_id: 4 },
  { id: 708, name: "Deir Tamich", district_id: 4 },
  { id: 709, name: "Roumieh", district_id: 4 },
  { id: 710, name: "Zaroun", district_id: 4 },
  { id: 711, name: "Zakrit", district_id: 4 },
  { id: 712, name: "Saqiyat Al Misk", district_id: 4 },
  { id: 713, name: "Bahr Safa", district_id: 4 },
  { id: 714, name: "Sin El Fil", district_id: 4 },
  { id: 715, name: "Dahr Al Sawan", district_id: 4 },
  { id: 716, name: "Ain Al Safsaf", district_id: 4 },
  { id: 717, name: "Mar Mikhael Bnabeel", district_id: 4 },
  { id: 718, name: "Ain Saadeh", district_id: 4 },
  { id: 719, name: "Aintoura", district_id: 4 },
  { id: 720, name: "Qarnet Al Hamra", district_id: 4 },
  { id: 721, name: "Qornet Chehwan", district_id: 4 },
  { id: 722, name: "Ain Aar", district_id: 4 },
  { id: 723, name: "Beit El Kako", district_id: 4 },
  { id: 724, name: "Qannabet Brummana", district_id: 4 },
  { id: 725, name: "Kfarteyh", district_id: 4 },
  { id: 726, name: "Kfar Aqab", district_id: 4 },
  { id: 727, name: "Mar Chaya", district_id: 4 },
  { id: 728, name: "Al Mazkeh", district_id: 4 },
  { id: 729, name: "Mar Mousa Al Dwar", district_id: 4 },
  { id: 730, name: "Majdal Tarshish", district_id: 4 },
  { id: 731, name: "Marjaba", district_id: 4 },
  { id: 732, name: "Mazraat Yashouh", district_id: 4 },
  { id: 733, name: "Nabiyeh", district_id: 4 },
  { id: 734, name: "Wata Al Mrouj", district_id: 4 },
  { id: 735, name: "Ghabet Boulonia", district_id: 4 },
  { id: 736, name: "Tripoli City", district_id: 8 },
  { id: 737, name: "Al Mina City", district_id: 8 },
  { id: 738, name: "Al Qalamoun", district_id: 8 },
  { id: 739, name: "Ajdabra", district_id: 11 },
  { id: 740, name: "Addeh", district_id: 11 },
  { id: 741, name: "Asiya", district_id: 11 },
  { id: 742, name: "Al Batroun", district_id: 11 },
  { id: 743, name: "Al Hari", district_id: 11 },
  { id: 744, name: "Bshaala", district_id: 11 },
  { id: 745, name: "Baqsima", district_id: 11 },
  { id: 746, name: "Beit Shalala", district_id: 11 },
  { id: 747, name: "Tahoum", district_id: 11 },
  { id: 748, name: "Tannourine Al Faouqa", district_id: 11 },
  { id: 749, name: "Tannourine Al Tahta", district_id: 11 },
  { id: 750, name: "Wata Houb", district_id: 11 },
  { id: 751, name: "Jran", district_id: 11 },
  { id: 752, name: "Hamat", district_id: 11 },
  { id: 753, name: "Hardine", district_id: 11 },
  { id: 754, name: "Douma", district_id: 11 },
  { id: 755, name: "Deir Bala", district_id: 11 },
  { id: 756, name: "Ras Nhash", district_id: 11 },
  { id: 757, name: "Zane", district_id: 11 },
  { id: 758, name: "Slaata", district_id: 11 },
  { id: 759, name: "Shatine", district_id: 11 },
  { id: 760, name: "Shabtine", district_id: 11 },
  { id: 761, name: "Shikka", district_id: 11 },
  { id: 762, name: "Abreen", district_id: 11 },
  { id: 763, name: "Kfarhilda", district_id: 11 },
  { id: 764, name: "Kfarhi", district_id: 11 },
  { id: 765, name: "Kfarabida", district_id: 11 },
  { id: 766, name: "Kfour Al Arabi", district_id: 11 },
  { id: 767, name: "Kouba", district_id: 11 },
  { id: 768, name: "Kour", district_id: 11 },
  { id: 769, name: "Mahmarsh", district_id: 11 },
  { id: 770, name: "Bane", district_id: 10 },
  { id: 771, name: "Barhlayoun", district_id: 10 },
  { id: 772, name: "Bzaoun", district_id: 10 },
  { id: 773, name: "Bsharri", district_id: 10 },
  { id: 774, name: "Bqaakafra", district_id: 10 },
  { id: 775, name: "Bqarqasha", district_id: 10 },
  { id: 776, name: "Hadat Al Jabal", district_id: 10 },
  { id: 777, name: "Hadchit", district_id: 10 },
  { id: 778, name: "Hasroun", district_id: 10 },
  { id: 779, name: "Tourza", district_id: 10 },
  { id: 780, name: "Abdine", district_id: 10 },
  { id: 781, name: "Qnat", district_id: 10 },
  { id: 816, name: "Ardeh", district_id: 9 },
  { id: 817, name: "Harf Ardeh", district_id: 9 },
  { id: 818, name: "Beit Aakar", district_id: 9 },
  { id: 819, name: "Beit Obeid", district_id: 9 },
  { id: 820, name: "Al Bahira", district_id: 9 },
  { id: 821, name: "Ayto", district_id: 9 },
  { id: 822, name: "Ayyal", district_id: 9 },
  { id: 823, name: "Baslouqayt", district_id: 9 },
  { id: 824, name: "Banshae", district_id: 9 },
  { id: 825, name: "Toula Al Jabal", district_id: 9 },
  { id: 826, name: "Aslout", district_id: 9 },
  { id: 827, name: "Harat Al Fawar", district_id: 9 },
  { id: 828, name: "Darya", district_id: 9 },
  { id: 829, name: "Bshnine", district_id: 9 },
  { id: 830, name: "Raskifa", district_id: 9 },
  { id: 831, name: "Rashain", district_id: 9 },
  { id: 832, name: "Zgharta", district_id: 9 },
  { id: 833, name: "Sbaal", district_id: 9 },
  { id: 834, name: "Saraal", district_id: 9 },
  { id: 835, name: "Arabt Qazhiya", district_id: 9 },
  { id: 836, name: "Arajis", district_id: 9 },
  { id: 837, name: "Ashash", district_id: 9 },
  { id: 838, name: "Alma", district_id: 9 },
  { id: 839, name: "Aintourine", district_id: 9 },
  { id: 840, name: "Qara Bash", district_id: 9 },
  { id: 841, name: "Karm Saddeh", district_id: 9 },
  { id: 842, name: "Kfar Hata", district_id: 9 },
  { id: 843, name: "Kfar Dallaqous", district_id: 9 },
  { id: 844, name: "Kfar Zayna", district_id: 9 },
  { id: 845, name: "Kfar Sghab", district_id: 9 },
  { id: 846, name: "Kfarfo", district_id: 9 },
  { id: 847, name: "Kfar Yachit", district_id: 9 },
  { id: 848, name: "Majdalya", district_id: 9 },
  { id: 849, name: "Mrayta", district_id: 9 },
  { id: 850, name: "Al Qadiriya", district_id: 9 },
  { id: 851, name: "Mazraat Al Tuffah", district_id: 9 },
  { id: 852, name: "Miziara", district_id: 9 },
  { id: 853, name: "Harf Miziara", district_id: 9 },
  { id: 854, name: "Hmees", district_id: 9 },
  { id: 855, name: "Ajd Abreen", district_id: 12 },
  { id: 856, name: "Al Majdal", district_id: 12 },
  { id: 857, name: "Al Nakhleh", district_id: 12 },
  { id: 858, name: "Harat Al Khassa", district_id: 12 },
  { id: 859, name: "Amioun", district_id: 12 },
  { id: 860, name: "Anfeh", district_id: 12 },
  { id: 861, name: "Batroumine", district_id: 12 },
  { id: 862, name: "Btaaboura", district_id: 12 },
  { id: 863, name: "Btourayej", district_id: 12 },
  { id: 864, name: "Bedba", district_id: 12 },
  { id: 865, name: "Bednayel", district_id: 12 },
  { id: 866, name: "Barsa", district_id: 12 },
  { id: 867, name: "Bzizza", district_id: 12 },
  { id: 868, name: "Bshamzin", district_id: 12 },
  { id: 869, name: "Bsarma", district_id: 12 },
  { id: 870, name: "Batram", district_id: 12 },
  { id: 871, name: "Bkiftin", district_id: 12 },
  { id: 872, name: "Dar Baashtar", district_id: 12 },
  { id: 873, name: "Dar Shamzin", district_id: 12 },
  { id: 874, name: "Deddeh", district_id: 12 },
  { id: 875, name: "Ras Masqa", district_id: 12 },
  { id: 876, name: "Rashdbine", district_id: 12 },
  { id: 877, name: "Zakroun", district_id: 12 },
  { id: 878, name: "Aaba", district_id: 12 },
  { id: 879, name: "Ansadik", district_id: 12 },
  { id: 880, name: "Ain Akrine", district_id: 12 },
  { id: 881, name: "Fyeh", district_id: 12 },
  { id: 882, name: "Qalhat", district_id: 12 },
  { id: 883, name: "Kaftoun", district_id: 12 },
  { id: 884, name: "Kfar Hata", district_id: 12 },
  { id: 885, name: "Kfar Hazir", district_id: 12 },
  { id: 886, name: "Kfar Saroun", district_id: 12 },
  { id: 887, name: "Kfar Aaqa", district_id: 12 },
  { id: 888, name: "Kfar Qahel", district_id: 12 },
  { id: 889, name: "Kfarya", district_id: 12 },
  { id: 890, name: "Kousba", district_id: 12 },
  { id: 891, name: "Matrit", district_id: 12 },
  { id: 892, name: "Al Beddawi", district_id: 13 },
  { id: 893, name: "Al Hazmiyeh", district_id: 13 },
  { id: 894, name: "Al Safira", district_id: 13 },
  { id: 895, name: "Al Qatteen", district_id: 13 },
  { id: 896, name: "Al Minyeh", district_id: 13 },
  { id: 897, name: "Al Nabi Youshaa", district_id: 13 },
  { id: 898, name: "Ayzal", district_id: 13 },
  { id: 899, name: "Bahneen", district_id: 13 },
  { id: 900, name: "Mazraat Artousa", district_id: 13 },
  { id: 901, name: "Al Rayhaniyeh", district_id: 13 },
  { id: 902, name: "Bahwayta", district_id: 13 },
  { id: 903, name: "Afqa", district_id: 13 },
  { id: 904, name: "Bshnata", district_id: 13 },
  { id: 905, name: "Bakhoun", district_id: 13 },
  { id: 906, name: "Burj Al Yahoudiya", district_id: 13 },
  { id: 907, name: "Batarmaz", district_id: 13 },
  { id: 908, name: "Bqaa Sfarine", district_id: 13 },
  { id: 909, name: "Bqarsouna", district_id: 13 },
  { id: 910, name: "Beit Al Fekes", district_id: 13 },
  { id: 911, name: "Harf Sayyad", district_id: 13 },
  { id: 912, name: "Haql Al Azimeh", district_id: 13 },
  { id: 913, name: "Deir Amar", district_id: 13 },
  { id: 914, name: "Deir Nbouh", district_id: 13 },
  { id: 915, name: "Seer", district_id: 13 },
  { id: 916, name: "Taran", district_id: 13 },
  { id: 917, name: "Aassoun", district_id: 13 },
  { id: 918, name: "Azqi", district_id: 13 },
  { id: 919, name: "Aymar", district_id: 13 },
  { id: 920, name: "Ain Al Tineh", district_id: 13 },
  { id: 921, name: "Qarsayta", district_id: 13 },
  { id: 922, name: "Karm Al Mihr", district_id: 13 },
  { id: 923, name: "Kfarbnine", district_id: 13 },
  { id: 924, name: "Kfarhabou", district_id: 13 },
  { id: 925, name: "Kfarshlan", district_id: 13 },
  { id: 926, name: "Marah Al Siraj", district_id: 13 },
  { id: 927, name: "Marah Al Safira", district_id: 13 },
  { id: 928, name: "Markabta", district_id: 13 },
  { id: 929, name: "Nmrine", district_id: 13 },
  { id: 930, name: "Wadi Al Nahleh", district_id: 13 },
  { id: 931, name: "Akroum", district_id: 14 },
  { id: 932, name: "Al Burj", district_id: 14 },
  { id: 933, name: "Al Bira", district_id: 14 },
  { id: 934, name: "Al Talil", district_id: 14 },
  { id: 935, name: "Al Jadideh", district_id: 14 },
  { id: 936, name: "Al Hamira", district_id: 14 },
  { id: 937, name: "Al Hawaysh", district_id: 14 },
  { id: 938, name: "Al Hayesa", district_id: 14 },
  { id: 939, name: "Al Dababiya", district_id: 14 },
  { id: 940, name: "Al Daghlah", district_id: 14 },
  { id: 941, name: "Al Dura", district_id: 14 },
  { id: 942, name: "Al Dousa", district_id: 14 },
  { id: 943, name: "Baghdadi", district_id: 14 },
  { id: 944, name: "Al Rayhaniya", district_id: 14 },
  { id: 945, name: "Al Zawarib", district_id: 14 },
  { id: 946, name: "Al Sahla", district_id: 14 },
  { id: 947, name: "Al Suwaysa", district_id: 14 },
  { id: 948, name: "Al Shaqdouf", district_id: 14 },
  { id: 949, name: "Al Sheikh Taba", district_id: 14 },
  { id: 950, name: "Al Sheikh Ayash", district_id: 14 },
  { id: 951, name: "Al Sheikh Mohammed", district_id: 14 },
  { id: 952, name: "Al Aboudiya", district_id: 14 },
  { id: 953, name: "Al Amayer", district_id: 14 },
  { id: 954, name: "Rajem Issa", district_id: 14 },
  { id: 955, name: "Al Awada", district_id: 14 },
  { id: 956, name: "Al Awaynat", district_id: 14 },
  { id: 957, name: "Al Oyoun", district_id: 14 },
  { id: 958, name: "Al Ghazayla", district_id: 14 },
  { id: 959, name: "Al Fard", district_id: 14 },
  { id: 960, name: "Al Qbayat", district_id: 14 },
  { id: 961, name: "Al Qarqaf", district_id: 14 },
  { id: 962, name: "Al Qurna", district_id: 14 },
  { id: 963, name: "Al Quriyat", district_id: 14 },
  { id: 964, name: "Al Qlayaat", district_id: 14 },
  { id: 965, name: "Al Qantara", district_id: 14 },
  { id: 966, name: "Al Kawashra", district_id: 14 },
  { id: 967, name: "Al Kwaykhat", district_id: 14 },
  { id: 968, name: "Al Majdal", district_id: 14 },
  { id: 969, name: "Al Muhammara", district_id: 14 },
  { id: 970, name: "Al Masoudiya", district_id: 14 },
  { id: 971, name: "Al Maqaybila", district_id: 14 },
  { id: 972, name: "Al Maqyataa", district_id: 14 },
  { id: 973, name: "Qaabrine", district_id: 14 },
  { id: 974, name: "Kfarmalki", district_id: 14 },
  { id: 975, name: "Al Ramoul", district_id: 14 },
  { id: 976, name: "Al Mounsa", district_id: 14 },
  { id: 977, name: "Al Nafisa", district_id: 14 },
  { id: 978, name: "Al Nahriya", district_id: 14 },
  { id: 979, name: "Bustan Al Harsh", district_id: 14 },
  { id: 980, name: "Al Noura", district_id: 14 },
  { id: 981, name: "Al Haycha", district_id: 14 },
  { id: 982, name: "Aylat", district_id: 14 },
  { id: 983, name: "Bbennine", district_id: 14 },
  { id: 984, name: "Al Abda", district_id: 14 },
  { id: 985, name: "Barbara", district_id: 14 },
  { id: 986, name: "Burj Al Arab", district_id: 14 },
  { id: 987, name: "Barqayel", district_id: 14 },
  { id: 988, name: "Bzal", district_id: 14 },
  { id: 989, name: "Bzebina", district_id: 14 },
  { id: 990, name: "Bqarzala", district_id: 14 },
  { id: 991, name: "Bani Sakhr", district_id: 14 },
  { id: 992, name: "Beit Al Haj", district_id: 14 },
  { id: 993, name: "Beit Ayoub", district_id: 14 },
  { id: 994, name: "Beit Millat", district_id: 14 },
  { id: 995, name: "Beit Younes", district_id: 14 },
  { id: 996, name: "Baino", district_id: 14 },
  { id: 997, name: "Qaboula", district_id: 14 },
  { id: 998, name: "Tashae", district_id: 14 },
  { id: 999, name: "Takrit", district_id: 14 },
  { id: 1000, name: "Talbira", district_id: 14 },
  { id: 1001, name: "Talha wa Shataha", district_id: 14 },
  { id: 1002, name: "Tall Abbas Sharqi", district_id: 14 },
  { id: 1003, name: "Tall Abbas Gharbi", district_id: 14 },
  { id: 1004, name: "Tall Mayan", district_id: 14 },
  { id: 1005, name: "Gabriel", district_id: 14 },
  { id: 1006, name: "Jadidet Al Qaytaa", district_id: 14 },
  { id: 1007, name: "Jarmanaya", district_id: 14 },
  { id: 1008, name: "Al Rama", district_id: 14 },
  { id: 1009, name: "Harrar", district_id: 14 },
  { id: 1010, name: "Halba", district_id: 14 },
  { id: 1011, name: "Hayzuq", district_id: 14 },
  { id: 1012, name: "Khirbet Daoud", district_id: 14 },
  { id: 1013, name: "Kfar Al Futouh", district_id: 14 },
  { id: 1014, name: "Khirbet Shaar", district_id: 14 },
  { id: 1015, name: "Kharayeb Al Jundi", district_id: 14 },
  { id: 1016, name: "Khatt Al Petrol", district_id: 14 },
  { id: 1017, name: "Douwayr Adawiya", district_id: 14 },
  { id: 1018, name: "Deir Janine", district_id: 14 },
  { id: 1019, name: "Deir Daloum", district_id: 14 },
  { id: 1020, name: "Dhouq Al Maksharin", district_id: 14 },
  { id: 1021, name: "Dhouq Al Hasniya", district_id: 14 },
  { id: 1022, name: "Dhouq Hadara", district_id: 14 },
  { id: 1023, name: "Rahba", district_id: 14 },
  { id: 1024, name: "Rammah", district_id: 14 },
  { id: 1025, name: "Safinat Al Drayb", district_id: 14 },
  { id: 1026, name: "Safinat Al Qaytaa", district_id: 14 },
  { id: 1027, name: "Sandyanat Raydan", district_id: 14 },
  { id: 1028, name: "Saysouq", district_id: 14 },
  { id: 1029, name: "Shan", district_id: 14 },
  { id: 1030, name: "Shadra", district_id: 14 },
  { id: 1031, name: "Sharbila", district_id: 14 },
  { id: 1032, name: "Dahr Al Qanbar", district_id: 14 },
  { id: 1033, name: "Dahr Al Leysina", district_id: 14 },
  { id: 1034, name: "Adbil", district_id: 14 },
  { id: 1035, name: "Aarqa", district_id: 14 },
  { id: 1036, name: "Akkar Al Atiqa", district_id: 14 },
  { id: 1037, name: "Ammar Al Baykat", district_id: 14 },
  { id: 1038, name: "Andqat", district_id: 14 },
  { id: 1039, name: "Ayat", district_id: 14 },
  { id: 1040, name: "Aydamoun", district_id: 14 },
  { id: 1041, name: "Sheikh Lar", district_id: 14 },
  { id: 1042, name: "Ain Al Thahab", district_id: 14 },
  { id: 1043, name: "Ain Al Zayt", district_id: 14 },
  { id: 1044, name: "Ain Yaqoub", district_id: 14 },
  { id: 1045, name: "Oyoun Al Ghazalan", district_id: 14 },
  { id: 1046, name: "Fasqin", district_id: 14 },
  { id: 1047, name: "Ain Ashma", district_id: 14 },
  { id: 1048, name: "Ain Tanta", district_id: 14 },
  { id: 1049, name: "Fneideq", district_id: 14 },
  { id: 1050, name: "Qabu Shamra", district_id: 14 },
  { id: 1051, name: "Qabeait", district_id: 14 },
  { id: 1052, name: "Qashlaq", district_id: 14 },
  { id: 1053, name: "Qinnaya", district_id: 14 },
  { id: 1054, name: "Karm Asfour", district_id: 14 },
  { id: 1055, name: "Beit Ghattas", district_id: 14 },
  { id: 1056, name: "Kurum Arab", district_id: 14 },
  { id: 1057, name: "Kfartoun", district_id: 14 },
  { id: 1058, name: "Kousha", district_id: 14 },
  { id: 1059, name: "Mar Touma", district_id: 14 },
  { id: 1060, name: "Majdala", district_id: 14 },
  { id: 1061, name: "Mazraat Balda", district_id: 14 },
  { id: 1062, name: "Mashta Hassan", district_id: 14 },
  { id: 1063, name: "Mashta Hammoud", district_id: 14 },
  { id: 1064, name: "Mashha", district_id: 14 },
  { id: 1065, name: "Mashmash", district_id: 14 },
  { id: 1066, name: "Mashlehat Al Hakour", district_id: 14 },
  { id: 1067, name: "Mamnaa", district_id: 14 },
  { id: 1068, name: "Mounjaz", district_id: 14 },
  { id: 1069, name: "Minyara", district_id: 14 },
  { id: 1070, name: "Haytla", district_id: 14 },
  { id: 1071, name: "Wadi Al Jamous", district_id: 14 },
  { id: 1072, name: "Wadi Al Hoor", district_id: 14 },
  { id: 1073, name: "Wadi Khaled", district_id: 14 },
  { id: 1104, name: "Ablah", district_id: 15 },
  { id: 1105, name: "Al Farzil", district_id: 15 },
  { id: 1106, name: "Al Marjiyat", district_id: 15 },
  { id: 1107, name: "Al Nasiriya", district_id: 15 },
  { id: 1108, name: "Al Nabi Ayla", district_id: 15 },
  { id: 1109, name: "Bar Elias", district_id: 15 },
  { id: 1110, name: "Bawarj", district_id: 15 },
  { id: 1111, name: "Terbol", district_id: 15 },
  { id: 1112, name: "Taalbaya", district_id: 15 },
  { id: 1113, name: "Jdita", district_id: 15 },
  { id: 1114, name: "Hazerta", district_id: 15 },
  { id: 1115, name: "Hay Al Fikani", district_id: 15 },
  { id: 1116, name: "Deir Al Ghazal", district_id: 15 },
  { id: 1117, name: "Rayat", district_id: 15 },
  { id: 1118, name: "Riyaq", district_id: 15 },
  { id: 1119, name: "Housh Hala", district_id: 15 },
  { id: 1120, name: "Zahle", district_id: 15 },
  { id: 1121, name: "Zahle - Maalaqa", district_id: 15 },
  { id: 1122, name: "Al Twayta", district_id: 15 },
  { id: 1123, name: "Al Karma", district_id: 15 },
  { id: 1124, name: "Taanayel", district_id: 15 },
  { id: 1125, name: "Saadnayel", district_id: 15 },
  { id: 1126, name: "Shtoura", district_id: 15 },
  { id: 1127, name: "Ali Al Nahri", district_id: 15 },
  { id: 1128, name: "Anjar", district_id: 15 },
  { id: 1129, name: "Housh Moussa", district_id: 15 },
  { id: 1130, name: "Ain Kfarzabad", district_id: 15 },
  { id: 1131, name: "Qaa Al Rimm", district_id: 15 },
  { id: 1132, name: "Qab Elias", district_id: 15 },
  { id: 1133, name: "Wadi Al Dalm", district_id: 15 },
  { id: 1134, name: "Qoussaya", district_id: 15 },
  { id: 1135, name: "Kfarzabad", district_id: 15 },
  { id: 1136, name: "Masa", district_id: 15 },
  { id: 1137, name: "Majdal Anjar", district_id: 15 },
  { id: 1138, name: "Maksah", district_id: 15 },
  { id: 1139, name: "Niha", district_id: 15 },
  { id: 1140, name: "Al Khayyara", district_id: 18 },
  { id: 1141, name: "Al Rawda", district_id: 18 },
  { id: 1142, name: "Al Sultan Yaqoub Al Muwahhada", district_id: 18 },
  { id: 1143, name: "Al Suwayri", district_id: 18 },
  { id: 1144, name: "Al Qaroun", district_id: 18 },
  { id: 1145, name: "Al Marj", district_id: 18 },
  { id: 1146, name: "Al Manara", district_id: 18 },
  { id: 1147, name: "Al Mansoura", district_id: 18 },
  { id: 1148, name: "Bab Mareh", district_id: 18 },
  { id: 1149, name: "Baaloul", district_id: 18 },
  { id: 1150, name: "Tall Dhanoub", district_id: 18 },
  { id: 1151, name: "Jab Janine", district_id: 18 },
  { id: 1152, name: "Housh Al Harayma", district_id: 18 },
  { id: 1153, name: "Khirbet Qanfar", district_id: 18 },
  { id: 1154, name: "Zalaya", district_id: 18 },
  { id: 1155, name: "Sahmar", district_id: 18 },
  { id: 1156, name: "Saghbeen", district_id: 18 },
  { id: 1157, name: "Aana", district_id: 18 },
  { id: 1158, name: "Ameeq", district_id: 18 },
  { id: 1159, name: "Aytanit", district_id: 18 },
  { id: 1160, name: "Ain Al Tineh", district_id: 18 },
  { id: 1161, name: "Ain Zibdeh", district_id: 18 },
  { id: 1162, name: "Ghaza", district_id: 18 },
  { id: 1163, name: "Qleya", district_id: 18 },
  { id: 1164, name: "Kamed Al Lawz", district_id: 18 },
  { id: 1165, name: "Kfarya", district_id: 18 },
  { id: 1166, name: "Lala", district_id: 18 },
  { id: 1167, name: "Labaya", district_id: 18 },
  { id: 1168, name: "Mashghara", district_id: 18 },
  { id: 1169, name: "Maydoun", district_id: 18 },
  { id: 1170, name: "Lousya", district_id: 18 },
  { id: 1171, name: "Yahmur", district_id: 18 },
  { id: 1172, name: "Al Bira", district_id: 27 },
  { id: 1173, name: "Al Housh", district_id: 27 },
  { id: 1174, name: "Al Rafid", district_id: 27 },
  { id: 1175, name: "Al Aqaba", district_id: 27 },
  { id: 1176, name: "Al Mahidsa", district_id: 27 },
  { id: 1177, name: "Baka", district_id: 27 },
  { id: 1178, name: "Bakfiya", district_id: 27 },
  { id: 1179, name: "Beit Lahya", district_id: 27 },
  { id: 1180, name: "Tannoura", district_id: 27 },
  { id: 1181, name: "Halwa", district_id: 27 },
  { id: 1182, name: "Khirbet Rouha", district_id: 27 },
  { id: 1183, name: "Deir Al Ashaer", district_id: 27 },
  { id: 1184, name: "Rashaya", district_id: 27 },
  { id: 1185, name: "Dahr Al Ahmar", district_id: 27 },
  { id: 1186, name: "Aita Al Fukhar", district_id: 27 },
  { id: 1187, name: "Ayha", district_id: 27 },
  { id: 1188, name: "Ain Harsha", district_id: 27 },
  { id: 1189, name: "Ain Al Arab", district_id: 27 },
  { id: 1190, name: "Ain Ata", district_id: 27 },
  { id: 1191, name: "Kfardinis", district_id: 27 },
  { id: 1192, name: "Kfarqouq", district_id: 27 },
  { id: 1193, name: "Mazraat Salsata", district_id: 27 },
  { id: 1194, name: "Kfarmashki", district_id: 27 },
  { id: 1195, name: "Koukba", district_id: 27 },
  { id: 1196, name: "Majdal Balhees", district_id: 27 },
  { id: 1197, name: "Madoukha", district_id: 27 },
  { id: 1198, name: "Yanta", district_id: 27 },
  { id: 1199, name: "Al Ansar", district_id: 16 },
  { id: 1200, name: "Al Tawfiqiya", district_id: 16 },
  { id: 1201, name: "Al Kharayeb", district_id: 16 },
  { id: 1202, name: "Al Khidr", district_id: 16 },
  { id: 1203, name: "Al Ram", district_id: 16 },
  { id: 1204, name: "Al Jibbaneh", district_id: 16 },
  { id: 1205, name: "Al Zarazir", district_id: 16 },
  { id: 1206, name: "Al Saideh", district_id: 16 },
  { id: 1207, name: "Al Taybeh", district_id: 16 },
  { id: 1208, name: "Al Ain", district_id: 16 },
  { id: 1209, name: "Al Fakkaha", district_id: 16 },
  { id: 1210, name: "Al Jadideh", district_id: 16 },
  { id: 1211, name: "Al Qaa", district_id: 16 },
  { id: 1212, name: "Al Qadam", district_id: 16 },
  { id: 1213, name: "Al Kaniseh", district_id: 16 },
  { id: 1214, name: "Al Libwa", district_id: 16 },
  { id: 1215, name: "Al Nabi Chit", district_id: 16 },
  { id: 1216, name: "Al Nabi Othman", district_id: 16 },
  { id: 1217, name: "Al Yammouneh", district_id: 16 },
  { id: 1218, name: "Ayat", district_id: 16 },
  { id: 1219, name: "Btadai", district_id: 16 },
  { id: 1220, name: "Badnayel", district_id: 16 },
  { id: 1221, name: "Barqa", district_id: 16 },
  { id: 1222, name: "Brital", district_id: 16 },
  { id: 1223, name: "Bshwat", district_id: 16 },
  { id: 1224, name: "Baalbek", district_id: 16 },
  { id: 1225, name: "Boudai", district_id: 16 },
  { id: 1226, name: "Al Allaq", district_id: 16 },
  { id: 1227, name: "Beit Mishik", district_id: 16 },
  { id: 1228, name: "Beit Mishik", district_id: 16 },
  { id: 1229, name: "Temnin Al Tahta", district_id: 16 },
  { id: 1230, name: "Temnin Al Faouqa", district_id: 16 },
  { id: 1231, name: "Jbaa", district_id: 16 },
  { id: 1232, name: "Jboula", district_id: 16 },
  { id: 1233, name: "Janta", district_id: 16 },
  { id: 1234, name: "Haddath Baalbek", district_id: 16 },
  { id: 1235, name: "Harbta", district_id: 16 },
  { id: 1236, name: "Hazine", district_id: 16 },
  { id: 1237, name: "Halbeta", district_id: 16 },
  { id: 1238, name: "Hour Taala", district_id: 16 },
  { id: 1239, name: "Housh Al Rafiqa", district_id: 16 },
  { id: 1240, name: "Housh Al Nabi", district_id: 16 },
  { id: 1241, name: "Housh Barada", district_id: 16 },
  { id: 1242, name: "Housh Tall Safiya", district_id: 16 },
  { id: 1243, name: "Housh Snide", district_id: 16 },
  { id: 1244, name: "Dours", district_id: 16 },
  { id: 1245, name: "Deir Al Ahmar", district_id: 16 },
  { id: 1246, name: "Ras Baalbek", district_id: 16 },
  { id: 1247, name: "Rammasa", district_id: 16 },
  { id: 1248, name: "Zaboud", district_id: 16 },
  { id: 1249, name: "Saraain Al Tahta", district_id: 16 },
  { id: 1250, name: "Saraain Al Faouqa", district_id: 16 },
  { id: 1251, name: "Shat", district_id: 16 },
  { id: 1252, name: "Shleifa", district_id: 16 },
  { id: 1253, name: "Shamstar Gharbi Baalbek", district_id: 16 },
  { id: 1254, name: "Kfardan", district_id: 16 },
  { id: 1255, name: "Tariya", district_id: 16 },
  { id: 1256, name: "Talyya", district_id: 16 },
  { id: 1257, name: "Arsal", district_id: 16 },
  { id: 1258, name: "Aynata", district_id: 16 },
  { id: 1259, name: "Fallawi", district_id: 16 },
  { id: 1260, name: "Qarha", district_id: 16 },
  { id: 1261, name: "Qsarnaba", district_id: 16 },
  { id: 1262, name: "Qald Al Saba", district_id: 16 },
  { id: 1263, name: "Qlayleh", district_id: 16 },
  { id: 1264, name: "Al Harfoush", district_id: 16 },
  { id: 1265, name: "Majdaloun", district_id: 16 },
  { id: 1266, name: "Mazraat Al Soueidan", district_id: 16 },
  { id: 1267, name: "Mazraat Al Toot", district_id: 16 },
  { id: 1268, name: "Masnaa Al Zahra", district_id: 16 },
  { id: 1269, name: "Maraboun", district_id: 16 },
  { id: 1270, name: "Maqraq", district_id: 16 },
  { id: 1271, name: "Maqneh", district_id: 16 },
  { id: 1272, name: "Nabha Al Damdoum", district_id: 16 },
  { id: 1273, name: "Nabha Al Mahafira", district_id: 16 },
  { id: 1274, name: "Nahla", district_id: 16 },
  { id: 1275, name: "Wadi Faghra", district_id: 16 },
  { id: 1276, name: "Younine", district_id: 16 },
  { id: 1277, name: "Al Sharbine", district_id: 17 },
  { id: 1278, name: "Al Shawagheer Al Faouqa", district_id: 17 },
  { id: 1279, name: "Al Shawagheer Al Tahta", district_id: 17 },
  { id: 1280, name: "Al Qasr", district_id: 17 },
  { id: 1281, name: "Al Kawakh", district_id: 17 },
  { id: 1282, name: "Al Hermel", district_id: 17 },
  { id: 1283, name: "Jouar Al Hasheesh", district_id: 17 },
  { id: 1284, name: "Fissane", district_id: 17 },
  { id: 1285, name: "Mazraat Sajad", district_id: 17 },
  { id: 1286, name: "Sidon", district_id: 23 },
  { id: 1287, name: "Arzay", district_id: 23 },
  { id: 1288, name: "Arkay", district_id: 23 },
  { id: 1289, name: "Al Babiliyeh", district_id: 23 },
  { id: 1290, name: "Al Barramieh", district_id: 23 },
  { id: 1291, name: "Al Bisariyeh", district_id: 23 },
  { id: 1292, name: "Al Hajjeh", district_id: 23 },
  { id: 1293, name: "Al Kharayeb", district_id: 23 },
  { id: 1294, name: "Al Zarariyeh", district_id: 23 },
  { id: 1295, name: "Al Siksikiyyeh", district_id: 23 },
  { id: 1296, name: "Al Salhiyeh", district_id: 23 },
  { id: 1297, name: "Al Sarafand", district_id: 23 },
  { id: 1298, name: "Al Adousiyyeh", district_id: 23 },
  { id: 1299, name: "Al Ghaziyeh", district_id: 23 },
  { id: 1300, name: "Al Ghassaniyeh", district_id: 23 },
  { id: 1301, name: "Al Qariyeh", district_id: 23 },
  { id: 1302, name: "Al Loubiyeh", district_id: 23 },
  { id: 1303, name: "Al Marwaniyeh", district_id: 23 },
  { id: 1304, name: "Al Mamariyeh", district_id: 23 },
  { id: 1305, name: "Al Miyyeh w Miyyeh", district_id: 23 },
  { id: 1306, name: "Al Najjariyeh", district_id: 23 },
  { id: 1307, name: "Al Hilaliyeh", district_id: 23 },
  { id: 1308, name: "Ansariyeh", district_id: 23 },
  { id: 1309, name: "Barti", district_id: 23 },
  { id: 1310, name: "Bqasta", district_id: 23 },
  { id: 1311, name: "Bnaafoul", district_id: 23 },
  { id: 1312, name: "Tfahhta", district_id: 23 },
  { id: 1313, name: "Harat Sidon", district_id: 23 },
  { id: 1314, name: "Khartoum", district_id: 23 },
  { id: 1315, name: "Darb Al Seem", district_id: 23 },
  { id: 1316, name: "Zayta", district_id: 23 },
  { id: 1317, name: "Tabaya", district_id: 23 },
  { id: 1318, name: "Tanbourit", district_id: 23 },
  { id: 1319, name: "Abra", district_id: 23 },
  { id: 1320, name: "Adloun", district_id: 23 },
  { id: 1321, name: "Aqtanit", district_id: 23 },
  { id: 1322, name: "Anqoun", district_id: 23 },
  { id: 1323, name: "Ain Al Dalb", district_id: 23 },
  { id: 1324, name: "Qaqaiyat Al Snoubar", district_id: 23 },
  { id: 1325, name: "Qannarit", district_id: 23 },
  { id: 1326, name: "Kfaryet", district_id: 23 },
  { id: 1327, name: "Kfarhatta", district_id: 23 },
  { id: 1328, name: "Kfarshallal", district_id: 23 },
  { id: 1329, name: "Kfarmalki", district_id: 23 },
  { id: 1330, name: "Kawthariyet Al Sayyad", district_id: 23 },
  { id: 1331, name: "Majdalyoune", district_id: 23 },
  { id: 1332, name: "Maghdousheh", district_id: 23 },
  { id: 1333, name: "Arzoun", district_id: 24 },
  { id: 1334, name: "Al Bazouriyeh", district_id: 24 },
  { id: 1335, name: "Al Barghaliyeh", district_id: 24 },
  { id: 1336, name: "Al Bustan", district_id: 24 },
  { id: 1337, name: "Al Bayyadh", district_id: 24 },
  { id: 1338, name: "Al Jebbayn", district_id: 24 },
  { id: 1339, name: "Al Haloussiyeh", district_id: 24 },
  { id: 1340, name: "Al Humairi", district_id: 24 },
  { id: 1341, name: "Al Haniyeh", district_id: 24 },
  { id: 1342, name: "Al Rammadiyeh", district_id: 24 },
  { id: 1343, name: "Al Zaloutieh", district_id: 24 },
  { id: 1344, name: "Al Shaatiyyeh", district_id: 24 },
  { id: 1345, name: "Al Malikiyeh", district_id: 24 },
  { id: 1346, name: "Al Shihabiyeh", district_id: 24 },
  { id: 1347, name: "Al Dhahira", district_id: 24 },
  { id: 1348, name: "Al Abbasiyeh", district_id: 24 },
  { id: 1349, name: "Al Qalileh", district_id: 24 },
  { id: 1350, name: "Al Kaniseh", district_id: 24 },
  { id: 1351, name: "Al Majadel", district_id: 24 },
  { id: 1352, name: "Al Mansouri", district_id: 24 },
  { id: 1353, name: "Al Naqoura", district_id: 24 },
  { id: 1354, name: "Al Nafakhiyeh", district_id: 24 },
  { id: 1355, name: "Batouliyeh", district_id: 24 },
  { id: 1356, name: "Barish", district_id: 24 },
  { id: 1357, name: "Bafleyh", district_id: 24 },
  { id: 1358, name: "Bedyas", district_id: 24 },
  { id: 1359, name: "Burj Al Shamali", district_id: 24 },
  { id: 1360, name: "Burj Rahal", district_id: 24 },
  { id: 1361, name: "Ain Abou Abdullah", district_id: 24 },
  { id: 1362, name: "Ain Al Zarqa", district_id: 24 },
  { id: 1363, name: "Jibal Al Batm", district_id: 24 },
  { id: 1364, name: "Jennata", district_id: 24 },
  { id: 1365, name: "Jwayya", district_id: 24 },
  { id: 1366, name: "Hanawiya", district_id: 24 },
  { id: 1367, name: "Dabaal", district_id: 24 },
  { id: 1368, name: "Dardaghiya", district_id: 24 },
  { id: 1369, name: "Deir Aames", district_id: 24 },
  { id: 1370, name: "Deir Qanoun Al Nahr", district_id: 24 },
  { id: 1371, name: "Deir Qanoun Ras Al Ain", district_id: 24 },
  { id: 1372, name: "Deir Kifa", district_id: 24 },
  { id: 1373, name: "Rashknaniyeh", district_id: 24 },
  { id: 1374, name: "Zibqine", district_id: 24 },
  { id: 1375, name: "Salaa", district_id: 24 },
  { id: 1376, name: "Shahour", district_id: 24 },
  { id: 1377, name: "Shamaa", district_id: 24 },
  { id: 1378, name: "Shiheen", district_id: 24 },
  { id: 1379, name: "Sadiqayn", district_id: 24 },
  { id: 1380, name: "Srifa", district_id: 24 },
  { id: 1381, name: "Tyre", district_id: 24 },
  { id: 1382, name: "Toura", district_id: 24 },
  { id: 1383, name: "Tayr Harfa", district_id: 24 },
  { id: 1384, name: "Tayr Daba", district_id: 24 },
  { id: 1385, name: "Tayr Falsieh", district_id: 24 },
  { id: 1386, name: "Alma Al Shaab", district_id: 24 },
  { id: 1387, name: "Aitit", district_id: 24 },
  { id: 1388, name: "Ain Baal", district_id: 24 },
  { id: 1389, name: "Qana", district_id: 24 },
  { id: 1390, name: "Majdalzoun", district_id: 24 },
  { id: 1391, name: "Mahrouneh", district_id: 24 },
  { id: 1392, name: "Marwahin", district_id: 24 },
  { id: 1393, name: "Mazraat Msharaf", district_id: 24 },
  { id: 1394, name: "Maaraka", district_id: 24 },
  { id: 1395, name: "Maroub", district_id: 24 },
  { id: 1396, name: "Yarine", district_id: 24 },
  { id: 1397, name: "Yanouh", district_id: 24 },
  { id: 1398, name: "Arnoun", district_id: 19 },
  { id: 1399, name: "Al Doueir", district_id: 19 },
  { id: 1400, name: "Al Sharqiyyeh", district_id: 19 },
  { id: 1401, name: "Al Qasaybeh", district_id: 19 },
  { id: 1402, name: "Al Kfour", district_id: 19 },
  { id: 1403, name: "Al Nabatiyeh Al Tahta", district_id: 19 },
  { id: 1404, name: "Al Nabatiyeh Al Faouqa", district_id: 19 },
  { id: 1405, name: "Al Numairiyyeh", district_id: 19 },
  { id: 1406, name: "Ansar", district_id: 19 },
  { id: 1407, name: "Brayqa", district_id: 19 },
  { id: 1408, name: "Jbaa", district_id: 19 },
  { id: 1409, name: "Ain Bouswar", district_id: 19 },
  { id: 1410, name: "Jebchit", district_id: 19 },
  { id: 1411, name: "Jarjouh", district_id: 19 },
  { id: 1412, name: "Harouf", district_id: 19 },
  { id: 1413, name: "Haboush", district_id: 19 },
  { id: 1414, name: "Houmine Al Tahta", district_id: 19 },
  { id: 1415, name: "Houmine Al Faouqa", district_id: 19 },
  { id: 1416, name: "Deir Al Zahrani", district_id: 19 },
  { id: 1417, name: "Roumine", district_id: 19 },
  { id: 1418, name: "Zabdine", district_id: 19 },
  { id: 1419, name: "Zifta", district_id: 19 },
  { id: 1420, name: "Zoutar Al Sharqiyyeh", district_id: 19 },
  { id: 1421, name: "Zoutar Al Gharbiyyeh", district_id: 19 },
  { id: 1422, name: "Sayni", district_id: 19 },
  { id: 1423, name: "Shoukeen", district_id: 19 },
  { id: 1424, name: "Sarba", district_id: 19 },
  { id: 1425, name: "Seer Al Gharbiyyeh", district_id: 19 },
  { id: 1426, name: "Aaba", district_id: 19 },
  { id: 1427, name: "Adshit", district_id: 19 },
  { id: 1428, name: "Arabsalim", district_id: 19 },
  { id: 1429, name: "Azzeh", district_id: 19 },
  { id: 1430, name: "Ain Qana", district_id: 19 },
  { id: 1431, name: "Qaqaiyat Al Jisr", district_id: 19 },
  { id: 1432, name: "Kfartebnit", district_id: 19 },
  { id: 1433, name: "Kfarrouman", district_id: 19 },
  { id: 1434, name: "Kfarseer", district_id: 19 },
  { id: 1435, name: "Kfarfila", district_id: 19 },
  { id: 1436, name: "Mayfdoun", district_id: 19 },
  { id: 1437, name: "Yahmour", district_id: 19 },
  { id: 1438, name: "Al Khalawat", district_id: 20 },
  { id: 1439, name: "Al Dallafeh", district_id: 20 },
  { id: 1440, name: "Al Fardays", district_id: 20 },
  { id: 1441, name: "Al Kfeir", district_id: 20 },
  { id: 1442, name: "Al Mari", district_id: 20 },
  { id: 1443, name: "Al Majidiyyeh", district_id: 20 },
  { id: 1444, name: "Al Habbariyeh", district_id: 20 },
  { id: 1445, name: "Hasbaya", district_id: 20 },
  { id: 1446, name: "Rashaya Al Fukhar", district_id: 20 },
  { id: 1447, name: "Shebaa", district_id: 20 },
  { id: 1448, name: "Shwayya", district_id: 20 },
  { id: 1449, name: "Ain Qinya", district_id: 20 },
  { id: 1450, name: "Kfar Hammam", district_id: 20 },
  { id: 1451, name: "Kfar Shouba", district_id: 20 },
  { id: 1452, name: "Koukba", district_id: 20 },
  { id: 1453, name: "Marj Al Zuhour", district_id: 20 },
  { id: 1454, name: "Mims", district_id: 20 },
  { id: 1455, name: "Al Jumayjmeh", district_id: 22 },
  { id: 1456, name: "Al Saltaniyeh", district_id: 22 },
  { id: 1457, name: "Al Tayri", district_id: 22 },
  { id: 1458, name: "Al Ghandouriyeh", district_id: 22 },
  { id: 1459, name: "Al Qawzah", district_id: 22 },
  { id: 1460, name: "Burj Qallawiyeh", district_id: 22 },
  { id: 1461, name: "Braasheet", district_id: 22 },
  { id: 1462, name: "Bint Jbeil", district_id: 22 },
  { id: 1463, name: "Beit Leef", district_id: 22 },
  { id: 1464, name: "Beit Yahoun", district_id: 22 },
  { id: 1465, name: "Tebnine", district_id: 22 },
  { id: 1466, name: "Harees", district_id: 22 },
  { id: 1467, name: "Hanine", district_id: 22 },
  { id: 1468, name: "Haddatha", district_id: 22 },
  { id: 1469, name: "Khirbet Selm", district_id: 22 },
  { id: 1470, name: "Dibil", district_id: 22 },
  { id: 1471, name: "Deir Antar", district_id: 22 },
  { id: 1472, name: "Ramiyeh", district_id: 22 },
  { id: 1473, name: "Rashaf", district_id: 22 },
  { id: 1474, name: "Rmeish", district_id: 22 },
  { id: 1475, name: "Shaqra", district_id: 22 },
  { id: 1476, name: "Doubiyeh", district_id: 22 },
  { id: 1477, name: "Sarbine", district_id: 22 },
  { id: 1478, name: "Safad Al Batteekh", district_id: 22 },
  { id: 1479, name: "Aita Al Jabal", district_id: 22 },
  { id: 1480, name: "Aita Al Shaab", district_id: 22 },
  { id: 1481, name: "Aytaroun", district_id: 22 },
  { id: 1482, name: "Ain Ebel", district_id: 22 },
  { id: 1483, name: "Aynata", district_id: 22 },
  { id: 1484, name: "Faroun", district_id: 22 },
  { id: 1485, name: "Qallawiyeh", district_id: 22 },
  { id: 1486, name: "Kafra", district_id: 22 },
  { id: 1487, name: "Kfardounine", district_id: 22 },
  { id: 1488, name: "Kounine", district_id: 22 },
  { id: 1489, name: "Maroun Al Ras", district_id: 22 },
  { id: 1490, name: "Yaroun", district_id: 22 },
  { id: 1491, name: "Yater", district_id: 22 },
  { id: 1492, name: "Aabel Al Saqi", district_id: 21 },
  { id: 1493, name: "Al Khiam", district_id: 21 },
  { id: 1494, name: "Al Sawana", district_id: 21 },
  { id: 1495, name: "Al Taybeh", district_id: 21 },
  { id: 1496, name: "Al Qalaiya", district_id: 21 },
  { id: 1497, name: "Al Qantara", district_id: 21 },
  { id: 1498, name: "Al Wazzani", district_id: 21 },
  { id: 1499, name: "Burj Al Mulouk", district_id: 21 },
  { id: 1500, name: "Ballat", district_id: 21 },
  { id: 1501, name: "Blayda", district_id: 21 },
  { id: 1502, name: "Bani Hayyan", district_id: 21 },
  { id: 1503, name: "Touline", district_id: 21 },
  { id: 1504, name: "Jadidet Marjaayoun", district_id: 21 },
  { id: 1505, name: "Houla", district_id: 21 },
  { id: 1506, name: "Dibbine", district_id: 21 },
  { id: 1507, name: "Deir Siryan", district_id: 21 },
  { id: 1508, name: "Deir Mimas", district_id: 21 },
  { id: 1509, name: "Rab Thalatheen", district_id: 21 },
  { id: 1510, name: "Talouseh", district_id: 21 },
  { id: 1511, name: "Adshit", district_id: 21 },
  { id: 1512, name: "Adayseh", district_id: 21 },
  { id: 1513, name: "Qabrikha", district_id: 21 },
  { id: 1514, name: "Kfarkila", district_id: 21 },
  { id: 1515, name: "Majdal Al Selm", district_id: 21 },
  { id: 1516, name: "Markaba", district_id: 21 },
  { id: 1517, name: "Meiss Al Jabal", district_id: 21 },
];

const electionTypes = [
  { id: 1, name: "Mayoral" },
  { id: 2, name: "Municipality" },
  { id: 3, name: "Parliamentary" },
  { id: 4, name: "Speaker" },
];

const genders = [
  { id: 1, name: "male" },
  { id: 2, name: "female" },
];

const maritalStatuses = [
  { id: 1, name: "single" },
  { id: 2, name: "married" },
  { id: 3, name: "divorced" },
  { id: 4, name: "windowed" },
];

const religions = [
  { id: 1, name: "islam" },
  { id: 2, name: "christianity" },
];

const denominations = [
  { id: 1, name: "sunni", religion_id: 1 },
  { id: 2, name: "shia", religion_id: 1 },
  { id: 3, name: "maronite", religion_id: 2 },
  { id: 4, name: "greek orthodox", religion_id: 2 },
  { id: 5, name: "greek catholic", religion_id: 2 },
  { id: 6, name: "armenian orthodox", religion_id: 2 },
  { id: 7, name: "armenian catholic", religion_id: 2 },
  { id: 8, name: "druze", religion_id: 1 },
  { id: 9, name: "alawite", religion_id: 1 },
  { id: 10, name: "minorities", religion_id: 2 },
];

module.exports = {
  governorates,
  constituencies,
  districts,
  villages,
  electionTypes,
  genders,
  maritalStatuses,
  denominations,
  religions,
};
